language: java
jdk:
    - oraclejdk7
    - oraclejdk8
before_install:
    - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
    - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
    - export JAVA_HOME=$JAVA8_HOME
script:
    - ./gradlew clean assemble check
