language: android
jdk:
    - openjdk7
    - openjdk8
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-android-m2repository
before_install:
    - export JAVA7_HOME=/usr/lib/jvm/java-7-openjdk-amd64
    - export JAVA8_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    - export JAVA_HOME=$JAVA8_HOME
script:
    - ./gradlew clean assemble check
